### ISSUE TITLE
Pressing Order Cards says that it is an illegal move

### ISSUE THREAD

**Issue by LozinALaifer** [simonk21/Ben#1]
Steps to Recreate:
1. Run the game
2. Press the Order Cards

...
N. When you run the game and choose, the game says that feature is an "illegal move". Though it is an application feature, it passes as a player move.

**Comment by simonk21** [comment]
Not too sure what you mean but we have implemented order cards button. However, it doesn't allow you to order cards when it's not your turn.

**Comment by LozinALaifer** [comment]
Sorry for not being specific, but the button works now. Good job!
