### ISSUE TITLE
Buttons Don't Work

### ISSUE THREAD

**Issue by dendinge21** [simonk21/Ben#6]
"Pause", "Leave Game", and "Order Cards" buttons do not do anything

1. Press "Start Game"
2. Play the game for a little
3. Press Pause, leave game, or order cards, nothing happens

**Comment by simonk21** [comment]
We implemented functionality for Leave Game and Order Cards, we removed Pause button and instead implemented a "Rules Info" Button

**Comment by dendinge21** [comment]
They fixed the issue!!
