### ISSUE TITLE
After you have no more cards to play

### ISSUE THREAD

**Issue by dendinge21** [simonk21/Ben#7]
1. Play the game until you no longer have any cards left in your hand.
2. The game is stuck on my turn, but I cannot play anything or click anything because I have no more cards to play

**Comment by simonk21** [comment]
The issue was that the passing method would sometimes work and sometimes not working depending on if the AI passed or played. We fixed it by implementing an instance variable that would keep track of who previously played and a while loop that would skip the turn of those who ran out of cards.

**Comment by dendinge21** [comment]
They fixed the issue!!!
